spring:
  config:
    activate:
      on-profile: db-local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/cody/data/test
    username: sa
    password: